### ISSUE TITLE
Exported textures turn out darker than original file

### ISSUE THREAD

**Issue by RQWorldblender** [Ploaj/SSBHLib#13]
Sample image:
![alp_snake_001_col](https://user-images.githubusercontent.com/13372387/50732978-3242c700-114a-11e9-98a8-1567564a415e.png)

Expected image (exported with [Switch-Toolbox](https://github.com/KillzXGaming/Switch-Toolbox)):
![alp_snake_001_col](https://user-images.githubusercontent.com/13372387/50732992-7635cc00-114a-11e9-9e1b-282688ee458d.png)

**Comment by Ploaj** [comment]
Which texture is that?
Looks like it needs to be gamma corrected.

**Comment by RQWorldblender** [comment]
That texture is for Solid Snake, his headband that's worn around his head.
