### ISSUE TITLE
ANIM export rotation

### ISSUE THREAD

**Issue by zrksyd** [Ploaj/SSBHLib#16]
I actually have found a manual fix for these issues, but it would be better to implement without me needing the manual fix regardless. The main issue is rotation values in an export ANIM use radians instead of degrees, so I multiply all the rotation values by (180 / pi) in Brawlbox. Secondly, for specifically Yoshi, his Snout and Cheek bones are inverted (I either had to multiply one of the rotation axes values by -1 or add 180 degrees. I forgot.)

**Comment by Ploaj** [comment]
I added it as an option for StudioSB export
https://github.com/Ploaj/StudioSB

It probably won't be added as an option for CrossMod
