### ISSUE TITLE
How do I export models?

### ISSUE THREAD

**Issue by ninetalescommander** [Ploaj/SSBHLib#23]
I'm trying to export the models but it's not letting me.
Back in Crossmod, I would just right-click the nutdlb, save it as an SMD, and then work from there.
I would just go back to Crossmod but for whatever reason, I can't seem to find a .zip on here that includes the .exe file.

**Comment by ScanMountGoat** [comment]
Cross mod is primarily an experimental research tool, so we don't provide binaries. You can compile the program from source using visual studio. For model imports/exports, use StudioSB instead. It can be found on Ploaj's github.

**Comment by ninetalescommander** [comment]
> Cross mod is primarily an experimental research tool, so we don't provide binaries. You can compile the program from source using visual studio. For model imports/exports, use StudioSB instead. It can be found on Ploaj's github.

Isn't it obvious I'm already using StudioSB? What else could this issue be referring to? Obviously it's not Crossmod because I explicitly state that I can't use that due to not having the program anymore.

**Comment by ninetalescommander** [comment]
Actually, I can now see the confusion, for some reason I thought SSBHLib included StudioSB and that's why I left the issue here.
Sorry about that.
