### ISSUE TITLE
AnimationBar Timer doesn't fire the Tick event in some situations

### ISSUE THREAD

**Issue by BenHall-7** [Ploaj/SSBHLib#24]
First test I can confirm is on Game & Watch, there are two issues immediately presented:
1. Animations can't play. When pressing the start/stop button, the click events are fired and the layout of the buttons are updated, but the timer itself seems to not run.
2. The AnimationBar buttons show an incorrect color on their inside for some reason.

I assume the amount of processing needed to render the fighter blocks up the thread and doesn't present an opportunity for the Tick event to fire, but can't confirm. I don't know what's wrong with the button color. 
![image](https://user-images.githubusercontent.com/22332781/67642529-ff3d1000-f8e2-11e9-99ff-334241e1f301.png)

**Comment by ScanMountGoat** [comment]
This is most likely cpu usage related as you mentioned. I can only reproduce the issue on my desktop while debugging. Timers don't have very reliable precision, so I'll look into other alternatives for scheduling animation updates.
