### ISSUE TITLE
CrossMod does not load models on my new PC

### ISSUE THREAD

**Issue by EyeDonutz** [Ploaj/SSBHLib#28]
For some reason the application does not load models anymore on my new PC (same applies to StudioSB). It gives off errors which are shown below. Tried deleting the shaders folder and reloading, didn't work.

![Screenshot](https://user-images.githubusercontent.com/54723981/82744341-7f185380-9dba-11ea-9344-b75ea91bb001.png)

With more details, the error gives this (in a txt file for convenience): 
[message.txt](https://github.com/Ploaj/SSBHLib/files/4672859/message.txt)

My new PC is meant to be a significant upgrade over the old one which could load models perfectly fine.

**Comment by ScanMountGoat** [comment]
What GPU do you have?

**Comment by EyeDonutz** [comment]
I have an Intel(R) UHD Graphics 630 I believe.

**Comment by ScanMountGoat** [comment]
Try again on the latest commit. There was a fixed issue with shaders not compiling on Intel. You need to click File > Reload Shaders and restart the application for everything to work properly. Let me know if it still doesn't work.

**Comment by ScanMountGoat** [comment]
Open a new issue if this happens again.
