### ISSUE TITLE
CrossMod exception upon loading models

### ISSUE THREAD

**Issue by ThatNintendoNerd** [Ploaj/SSBHLib#29]
Upon loading a folder with the latest commit of CrossMod to view a model, I am getting [this](https://pastebin.com/keCRH9ax) exception. Occurs with both vanilla and modded models.
I am using an NVIDIA GeForce GTX 970 GPU. I can provide more information if necessary.

**Comment by ScanMountGoat** [comment]
Try reloading the shaders to ensure the shader binaries are updated.

**Comment by ThatNintendoNerd** [comment]
No dice. The same exception occurs.

**Comment by ScanMountGoat** [comment]
Try reloading shaders on the latest commit. If it doesn't work, upload the txt files in the `ErrorLogs` folder.

**Comment by ThatNintendoNerd** [comment]
The latest commit seems to work just fine now. There's one warning (both the same) under "Program Errors" in each .txt file ([Error_Logs.zip](https://github.com/Ploaj/SSBHLib/files/4674593/Error_Logs.zip)), but that's beyond this issue, so this can now be closed.
