### ISSUE TITLE
Recent SSBHLib changes in StudioSB lead to pascal casing on vertex attributes with camel casing when saving NUMSHB

### ISSUE THREAD

**Issue by ThatNintendoNerd** [Ploaj/SSBHLib#32]
Wasn't sure if I should have created an issue here or the StudioSB repository, but since this is related to recent SSBHLib changes (as noted in the commit message) I thought I should post the issue here. If I need to move this issue to the StudioSB repository this can be closed and I can resubmit it there.

[Commit b4f2f07](https://github.com/Ploaj/StudioSB/commit/b4f2f07c84810fab15fe85a644a164719cf86150) in StudioSB causes vertex attributes with camel casing (map1, uvSet, colorSet1) to use pascal casing (Map1, UvSet, ColorSet1). The game cannot parse these vertex attributes correctly and causes the meshes to use the yellow checkerboard dummy texture to note missing vertex attributes expected in the material.

**Comment by ScanMountGoat** [comment]
Should be fixed on the latest. If something similar happens again, you can report it on StudioSB. I get notifications for both, so it isn't a huge deal which github page you post the issue on.
