### ISSUE TITLE
Models not loading and shader error/shader not compiling with the newest release

### ISSUE THREAD

**Issue by RagesBayo** [Ploaj/SSBHLib#34]
[RModel_shader_errors.txt](https://github.com/Ploaj/SSBHLib/files/4909895/RModel_shader_errors.txt)
[RModelDebug_shader_errors.txt](https://github.com/Ploaj/SSBHLib/files/4909896/RModelDebug_shader_errors.txt)

**Comment by ScanMountGoat** [comment]
I've updated the `Release.7z`. Try downloading again and let me know if it works.

**Comment by ThatNintendoNerd** [comment]
Can confirm the same exact shader compilation errors are occurring on this latest release, using an NVIDIA GPU as well. The updated release does not solve the compilation errors and is exactly the same.

**Comment by ScanMountGoat** [comment]
Try again on v0.2, which I just released. Nvidia's shader compiler is quite picky.

**Comment by RagesBayo** [comment]
It works now! However opening bayonetta seems to make the program crash

**Comment by ScanMountGoat** [comment]
@RagesBayo If you have encounter a separate bug, you can open a new issue with the name of the file and any error messages that get generated.
