### ISSUE TITLE
Fails to launch, latest release

### ISSUE THREAD

**Issue by Demonslayerx8** [Ploaj/SSBHLib#39]
Just as the title says, it just fails to launch now. Happens to TNN too.

I'm using Win10 Pro, version 1809

for TNN, Win10 Home, version 1903

**Comment by ScanMountGoat** [comment]
The .NET Core 3.1 desktop runtime is required to run the program now. The build got messed up while making some of the dependencies cross platform. The release has been updated and should be working now.
