### ISSUE TITLE
scaling parsed or read improperly on certain animations

### ISSUE THREAD

**Issue by tateplayer** [Ploaj/SSBHLib#4]
it seems that scaling is being read wrong on certain animations when imported into the viewer.

note this animation & model pair below -- this is boss/darz/model/body/model.numdlb with the animation boss/darz/motion/body/entry.nuanmb
![image](https://user-images.githubusercontent.com/21991592/50361450-cc86f600-0520-11e9-8482-6f69a39b749c.png)

exporting the animation to any format obviously uses these values and maintains the issue. however, if i disable scaling on export:
![image](https://user-images.githubusercontent.com/21991592/50361557-36070480-0521-11e9-80cd-d7dbec84a8b2.png)

then the issue disappears--so something seems to be invalid with the scaling when reading this animation.

**Comment by ScanMountGoat** [comment]
There were a number of issues with animation scale and scale inheritance. This will be fixed for the next release (v0.19).
![image](https://user-images.githubusercontent.com/23301691/135532651-bb71247c-b05a-4a84-b888-8b50d2f5a495.png)
