### ISSUE TITLE
Feature proposal : screenshot saving

### ISSUE THREAD

**Issue by Nixoup** [Ploaj/SSBHLib#46]
Hello !

I’m a Studio SB user and as a graphic design, I love so much your software !
I have discover Cross Mod, seems to be a same software (but better?) and I was surprised than « save screenshot » was unavailable 

It would be possible to add him? :)

**Comment by ScanMountGoat** [comment]
I'm glad you're enjoying the program. Studio SB has support for more formats and can import and export models and animations, which likely won't ever be supported in Cross Mod. Cross Mod has material editing and more accurate rendering than Studio SB. 

Cross Mod supports taking screenshots, but there aren't any buttons on the user interface for it. Screenshot support should be added in one of the next few releases and hopefully exporting images of animations as well.

**Comment by Nixoup** [comment]
Yes awesome ! Can't wait to see this, thanks again!
