### ISSUE TITLE
crash when trying to set bone buffer with 306 bones

### ISSUE THREAD

**Issue by SushiiZ** [Ploaj/SSBHLib#80]
![image](https://user-images.githubusercontent.com/51277271/133910080-493d8a27-6e62-459a-acb0-76eb55bd614e.png)

**Comment by ScanMountGoat** [comment]
This error shouldn't come up if the mesh was exported correctly. Can you upload the files in a zip so I can take a look at them? Github lets you drag the zip onto a comment to upload.

**Comment by SushiiZ** [comment]
ok, so the dealio is I'm trying something new with a commissioner, I didn't setup the model or anything, but yeah, ik it's crazy high poly  
also github isn't letting me use the gif

**Comment by SushiiZ** [comment]
https://drive.google.com/file/d/1-vK4etdDPjIpHNN88feCGiKEMCMzOmSi/view?usp=sharing

**Comment by ScanMountGoat** [comment]
Github was probably complaining about the large size. Thankfully, this is a quick fix. I need to modify the shaders to support more bones. This should be fixed for the next release (v0.18).
