### ISSUE TITLE
Camera is too zoomed out upon initial viewing of some models

### ISSUE THREAD

**Issue by ThatNintendoNerd** [Ploaj/SSBHLib#81]
Opening models like Mario in Cross Mod frames the model at a suitable distance and position. Selecting "Frame Model" will revert to the initial position as intended. This also applies to basic stage models like `stage/75m/norma/model/stc_stgdonkey_donkeykong_set/`.

Opening models like `stage/mario_past64/normal/model/ring_set/` causes the camera to be offset on every axes by tens of thousands of units. However, selecting "Frame Model" will position the camera at a less-than optimal position, but one that's more suitable. A model like `stage/75m/normal/model/stc_chikei_set/` will practically center the camera to the world but will zoom the camera out to precisely -200000.0 units. Selecting "Frame Model" will position the camera to a more suitable position for what the model is.

**Comment by ScanMountGoat** [comment]
This is similar to #56, but I'm going to leave both open for now. This is definitely something that I'd like to improve at some point.

**Comment by ThatNintendoNerd** [comment]
Resolved in Cross Mod 0.20.
