### ISSUE TITLE
Green Background

### ISSUE THREAD

**Issue by Entonement** [Ploaj/SSBHLib#97]
Hi, 

I tried to change the Background (Green) but it doesn't work even if I changed the value in ViewportRender.cs and rebuilt the project.
Is it normal ?

**Comment by Entonement** [comment]
After Build I export the file SsbhLib.dll in the folder who contians a last release of crossmod

**Comment by ScanMountGoat** [comment]
ViewportRenderer.cs is part of the CrossMod project, so you need to change CrossMod.dll.

**Comment by Entonement** [comment]
Okay I will try it but when I build, there is only Ssbhlib.dll et SsbhBatchProcess.dll

**Comment by ScanMountGoat** [comment]
I'm closing this since it's not a bug or feature request. Feel free to ask questions in this issue if you're still stuck.
