### ISSUE TITLE
Crossmod v20 doesn't list some Material Errors

### ISSUE THREAD

**Issue by CattailXC** [Ploaj/SSBHLib#98]
Specifically, Missing Required Attributes- colorset1. I don't know if this happens with other errors but it might. The top image is v19, which shows the missing attribute, and the second is v20, which shows the yellow checkerboard but not the error.

![image](https://user-images.githubusercontent.com/97373686/148668765-7008e640-3c6d-403c-87e6-a3783453af48.png)

![image](https://user-images.githubusercontent.com/97373686/148668814-cebb2bcf-39bc-4b7d-8013-302fade3776a.png)

First time submitting a github issue so I hope this was the right place for it.

**Comment by ScanMountGoat** [comment]
Thank you for reporting this. It should be fixed in the next release (v21).
